### PR TITLE
#6170 feat(style): change footer/header bg color; adds X- prefix for …

### PR DESCRIPTION
**Pull request by chriddell**
…deprecated colours

- changes header/footer bg color to deprecated blue
- adds X- legacy prefix to vars

### CODE REVIEW

**Review by creido-welly — APPROVED** [review]
Have you checked the site logo background?

**Comment by chriddell** [comment]
@creido good flag.

Ideally want to remove the background from the `.logo` selector, but noticed there are 3 logos there - the "medium" one is never visible, why is it there?

Screenshot 2020-02-25 at 09 48 35

**Comment by creido-welly** [comment]
> Ideally want to remove the background from the `.logo` selector, but noticed there are 3 logos there - the "medium" one is never visible, why is it there?

Yes ideally the logo would have a transparent background so it wouldn't matter if the header colour behind it changed

Re the 3 logos, the first one is used on mobile devices when the user is at the top of the page. Scrolling down changes between this and the cut down version.

**Comment by chriddell** [comment]
Of course! Thanks, couldn't tell what the third logo was doing there. Have updated the Header to hide the "medium" logo when non-sticky header, and removed bg.

**Pull request merged**
