### PR TITLE
bug: Storybook compatibility with npm link

### PR DESCRIPTION
**Pull request by creido-welly**
Upgraded storybook to release candidate for v6.1 to fix compatibility issue with "npm link".

Explanation: "npm link" is used heavily in development to link corporate-components to corporate-react as a live reloading dependency

### CODE REVIEW

**Review by chriddell — COMMENTED** [review]
Noticed we've lost ~40,000 lines from package-lock... have you pushed this without re-running `npm i` after npm linking corporate-components/react?

**Comment by creido-welly** [comment]
I'm pretty sure I re-ran npm i but will do it again just to be safe

**Comment by chriddell** [comment]
Could just be that storybook has way less dependencies...

**Review by chriddell — APPROVED** [review]

**Comment by creido-welly** [comment]
Slight difference but there's still a discrepancy of over 40,000 lines

**Pull request merged**
